### ISSUE TITLE
Test fails because it references "sal"

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france-data#105]
Execution of [test_fake_survey_simulation.py](https://github.com/openfisca/openfisca-france-data/blob/07637f3c6b392e16a0587fc776dad71de25a8831/openfisca_france_data/tests/test_fake_survey_simulation.py#L92) produces:

```
ERROR: openfisca_france_data.tests.test_fake_survey_simulation.test_fake_survey_simulation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/cbenz/Dev/openfisca/openfisca-france-data/openfisca_france_data/tests/test_fake_survey_simulation.py", line 92, in test_fake_survey_simulation
    sal = simulation.calculate('sal')
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/simulations.py", line 76, in calculate
    return self.compute(column_name, period = period, **parameters).array
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/simulations.py", line 156, in compute
    holder = self.get_or_new_holder(column_name)
  File "/home/cbenz/Dev/openfisca/openfisca-core/openfisca_core/simulations.py", line 231, in get_or_new_holder
    entity = self.entity_by_column_name[column_name]
KeyError: 'sal'
```

**Comment by benjello** [comment]
Obsolete
