### ISSUE TITLE
Pb with duplicated families/individuals when building ERFS_FPR in 2013

### ISSUE THREAD

**Issue by elie-gerschel** [openfisca/openfisca-france-data#182]
Hi there!

I really enjoy OpenFisca-France-Data, but I recently encountered an issue.

### Here is what I did:

survey_scenario = get_survey_scenario(
       tax_benefit_system = tax_benefit_system,
        year = 2013,
        rebuild_input_data = True,
        )

The traceback is below. I have put a temporary fix (dropping families which were duplicated) in 2013 and could see the same kind of fix had been implemented already for one family.
The issue deserves some investigation. 

### Here is the traceback

Traceback (most recent call last):

  File "<ipython-input-4-b68b0fd6db40>", line 24, in <module>
    rebuild_input_data = True,

  File "C:\Users\elieg\openfisca-france-data\openfisca_france_data\erfs_fpr\get_survey_scenario.py", line 86, in get_survey_scenario
    use_marginal_tax_rate = use_marginal_tax_rate,

  File "C:\Users\elieg\Anaconda3\envs\ipp\lib\site-packages\openfisca_survey_manager\scenarios.py", line 791, in init_from_data
    self.build_input_data(year = data_year)

  File "C:\Users\elieg\openfisca-france-data\openfisca_france_data\erfs_fpr\scenario.py", line 72, in build_input_data
    build(year = year)

  File "C:\Users\elieg\openfisca-france-data\openfisca_france_data\erfs_fpr\input_data_builder\__init__.py", line 50, in build
    famille.build_famille(year = year)

  File "C:\Users\elieg\Anaconda3\envs\ipp\lib\site-packages\openfisca_survey_manager\temporary.py", line 39, in func_wrapper
    return func(*args, temporary_store = temporary_store, **kwargs)

  File "C:\Users\elieg\openfisca-france-data\openfisca_france_data\erfs_fpr\input_data_builder\step_04_famille.py", line 98, in build_famille
    skip_enfants_a_naitre = skip_enfants_a_naitre)

  File "C:\Users\elieg\openfisca-france-data\openfisca_france_data\erfs_fpr\input_data_builder\step_04_famille.py", line 138, in create_familles
    year = year,

  File "C:\Users\elieg\openfisca-france-data\openfisca_france_data\erfs_fpr\input_data_builder\step_04_famille.py", line 675, in famille_5
    assert not famille.noindiv.duplicated().any()

AssertionError

## Context

I identify more as a:

- Economist _(I make microsimulations with real populations)_.
- Developer _(I create tools that use OpenFisca-France-Data)_.
- Commenter _(I make data visualisations)_.
- LexImpact _(I model reforms to make them exist)_.

(remove this line as well as all items in the list that don't fit your situation)

**Comment by maukoquiroga** [comment]
Hi @elie-gerschel thanks for reporting this issue. I'm not a Windows user myself but maybe @benjello, @claireleroy or @openfisca/france-contrib-ipp have already encountered this issue?
